require_all ENV['DOWNLOAD_URL']+'/command'
require_all ENV['DOWNLOAD_URL']+'/database'
require_all ENV['DOWNLOAD_URL']+'/helper'
require_all ENV['DOWNLOAD_URL']+'/is_true'
require_all ENV['DOWNLOAD_URL']+'/message'
