Metrics/LineLength:
  Max: 125

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 125

Metrics/AbcSize:
  Max: 35

Metrics/BlockNesting:
  Max: 5

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/RegexpLiteral:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

AllCops:
  Exclude:
    - '/project/bandung-telegram-bot/cron_job/reminder_normal.rb'
    - '/project/bandung-telegram-bot/cron_job/reminder_cron.rb'
    - '/project/bandung-telegram-bot/cron_job/cap_cron.rb'
    - '/project/bandung-telegram-bot/cron_job/rake_cron.rb'
    - '/project/bandung-telegram-bot/require/helper_cap.rb'
    - '/project/bandung-telegram-bot/require/helper_ruby.rb'
    - '/project/bandung-telegram-bot/require/ruby_cap.rb'
    - '/project/bandung-telegram-bot/require_ruby.rb'
    - '/project/bandung-telegram-bot/require_helper.rb'
    - '/project/bandung-telegram-bot/Gemfile'
    - '/project/bandung-telegram-bot/Gemfile.lock'
    - '/project/bandung-telegram-bot/helper/bot_detail.rb'
    - '/project/bandung-telegram-bot/database/crud.rb'
    - '/project/bandung-telegram-bot/helper/bot_weather.rb'
    - '/project/bandung-telegram-bot/command/list_keyboard.rb'
